server:
  port: 8765
spring:
  application:
    name: ecom-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/vaibhav-jadhav0512/ecommerce
          clone-on-start: true
          search-paths: 'config/{application}'
          default-label: main
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
  
