server:
  port: 8888
spring:
  application:
    name: ECOM-API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: ECOM-ORDER-SERVICE
          uri: lb://ECOM-ORDER-SERVICE
          predicates:
            - Path=/orders/**
        - id: ECOM-PRODUCT-SERVICE
          uri: lb://ECOM-PRODUCT-SERVICE
          predicates:
            - Path=/product/**
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
okta:
  oauth2:
    issuer: https://dev-25813495.okta.com/oauth2/default
    audience: api://default
    client-id: 0oaao9o5zyIWHzLKy5d7
    client-secret: RYdeUmHnTeHROrzOuUMPYSx-QDHLoR3vAqdADj3qvYi-GoI-n_ZHO9rCSqrnGXXe
    scopes: openid, profile, email, offline_access, vaibhav
