server:
  port: 8888
spring:
  application:
    name: ECOM-API-GATEWAY
  webflux:
    cors:
      allowed-origins: http://localhost:3001
  cloud:
    gateway:
      routes:
        - id: ECOM-ORDER-SERVICE
          uri: lb://ECOM-ORDER-SERVICE
          predicates:
            - Path=/orders/**
          filters:
            - AuthFilter
        - id: ECOM-PRODUCT-SERVICE
          uri: lb://ECOM-PRODUCT-SERVICE
          predicates:
            - Path=/product/**
          filters:
            - AuthFilter
        - id: ECOM-AUTHORIZATION-SERVER
          uri: lb://ECOM-AUTHORIZATION-SERVER
          predicates:
            - Path=/auth/**
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
