server:
  port: 9000
spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/product
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: PRODUCT-SERVICE
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
